### ISSUE TITLE
NAT中转如何配置ikago?

### ISSUE THREAD

**Issue by herman6888** [zhxie/ikago#5]
NAT中转如何配置ikago? 
家里虚拟机 > 国内NAT机 > 国外落地机 > Nintendo Servers

**Comment by zhxie** [comment]
It needs to be implemented through `SNAT` and `DNAT`, but since the network configuration varies from node to node, I cannot give a standard answer. If you have a SOCKS5 proxy, it is recommended to use [pcap2socks](https://github.com/zhxie/pcap2socks) or [pcap2socks-gui](https://github.com/zhxie/pcap2socks-gui). There are many cases of SOCKS5 proxy transit solutions in the network, which can be used for reference.

---

需要通过 `SNAT` 与 `DNAT` 实现，但由于网络配置因节点而异，我无法给出标准答案。如果你拥有 SOCKS5 代理，建议使用 [pcap2socks](https://github.com/zhxie/pcap2socks) 或 [pcap2socks-gui](https://github.com/zhxie/pcap2socks-gui)。SOCKS5 代理的中转解决方案在网络中的案例较多，可以用于参考。
